version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: hexa_taxi_redis
    restart: always
    networks:
      - hexa_taxi_network
    volumes:
      - ./volume/redis:/data
      
  db:
    image: postgres:alpine
    restart: always
    container_name: hexa_taxi_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=HEXA_TAXI@POSTGRES
      - POSTGRES_DB=postgres
    networks:
      - hexa_taxi_network
    volumes:
      - ./volume/postgres:/var/lib/postgresql/data

  backend:
    build: .
    container_name: hexa_taxi_backend
    environment:
      - SECRET_KEY=TaXIHeXAScetKey!@$!@#!@%$!@%!#!@$%!@%4123412314
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:HEXA_TAXI%40POSTGRES@db:5432/postgres
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=True
      - MAIL_USERNAME=hexa.unist@gmail.com
      - MAIL_PASSWORD=ubym bopf rbjn hmvq
      - MAIL_DEFAULT_SENDER=TaxiHeXA
      - REDIS_URL=redis://redis:6379
  
    depends_on:
      - db
      - redis
    ports:
      - "10001:8000"
    networks:
      - hexa_taxi_network

networks:
  hexa_taxi_network:
    name: hexa_taxi_network
    driver: bridge
